### ISSUE TITLE
[App-147]: add Code Style Analysis job as GitHub Actions workflow to run Rubocop on push

### ISSUE THREAD

**Issue by Thevel0per** [wta-fourty-love/application#236]
add Code Style Analysis job as GitHub Actions workflow to run Rubocop on push

**Comment by tmtocb** [comment]
@Thevel0per stylistic FYI: I have adjusted the title on this issue

a) always start the title with small letter
b) it's GitHub Actions not github action
c) please highlight keywords in the title with Big Letter
d) remember to fill issue description
